### ISSUE TITLE
Obfuscate file names?

### ISSUE THREAD

**Issue by aheckler** [woocommerce/sensei-media-attachments#22] opened 2017-11-13 14:45 UTC
If I'm selling a course via WooCommerce, I would ideally want to prevent media attachments on those courses from being publicly available. Maybe we can add some sort of obfuscation to the filename or path?

789471-zen

**Comment by donnapep** [comment] 2018-02-03 12:55
Closing as it sounds like a duplicate of #2.

**Closed by donnapep** 2018-02-03 12:55 UTC
Labels: [Type] Enhancement
